routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\EnrollmentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();

Route::get('/allusers', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::resource('student', StudentController::class);
//courses Route
Route::resource('course', CourseController::class);
//Teacher Route
Route::resource('teacher', TeacherController::class);
//Enrollment Route
Route::resource('enrollment', EnrollmentController::class);

app/Models/Enrollment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Enrollment extends Model
{
    use HasFactory;
    protected $table = 'enrollments';
    protected $primaryKey = 'id';
    protected $fillable = ['student_id','course_id','teacher_id'];

    public function student()
    {
        return $this->belongsTo(Student::class);
    }
    public function course()
    {
        return $this->belongsTo(Course::class);
    }
    public function teacher()
    {
        return $this->belongsTo(Teacher::class);
    }
}

app/Http/Controllers/EnrollmentController.php
<?php

namespace App\Http\Controllers;
use App\Models\Student;
use Illuminate\Support\Facades\Validator;
use App\Models\Course;
use App\Models\Teacher;
use App\Models\Enrollment;
use App\Helpers\Helper;
use Illuminate\Http\Request;

class EnrollmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $enrollment =  Enrollment::with('student','teacher','course')->get();
        return view('admin.enrollments.all_enrollment')->with('enrollment',$enrollment);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
          
        $student = Student::all();
        $course =  Course::all();
        $teacher = Teacher::all();
        $enrollment =  Enrollment::with('student','teacher','course')->get();
        return view('admin.enrollments.form', compact('student','course','teacher','enrollment'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $help = Helper::createenrollment($request);
        $request->validate($help);
        $input=$request->all();
        $student = Enrollment::create($input);
        $request->session()->flash('msg','Inserted Sucessfully!!');
        return redirect()->route('enrollment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //fetching data

        $student = Student::all();
        $course =  Course::all();
        $teacher = Teacher::all();
       $enrollment=Enrollment::where('id',$id)->first();
       if (is_null($enrollment)) {
         return "Record not Found";
       }
       return view ('admin.enrollments.form')->with(compact('student','course','teacher','enrollment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Helper::createenrollment($request,$id);
        $request->validate($update);
        $enrollment = Enrollment::find($id);
    
        $input=$request->all();
        $enrollment->update($input);
        $request->session()->flash('msg','update Sucessfully!!');
             return redirect()->route('enrollment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Enrollment::destroy($id);

        return response()->json(['status'=>'Enrollment Deleted Successfully']);
    }
}

resources/views/admin/enrollments/all_enrollment.blade.php
@extends("layouts.header")
@section('title', 'All Enrollments')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Enrollments</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    @if(Session::has('fahad'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('fahad')}}</div>
				</div>
				@endif
				@if(Session::has('msg'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('msg')}}</div>
				</div>
				@endif
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- table data -->
        <!-- /.row (main row) -->
        <div class="card">
              <div class="card-header text-end">
                <a href="{{route('enrollment.create')}}"  class="btn btn-primary">Add <span>+</span></a>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Student</th>
                    <th>Teacher</th>
                    <th>Course</th>
                    <th>Operations</th>
                  </tr>
                  </thead>
                  <tbody>
											@if($enrollment)
											@foreach($enrollment as $row)
											<tr class="odd">
                        <input type="hidden" class="delete_val" value="{{$row->id}}">
												<td>{{$row->id}}</td>
												<td>{{$row->student->name}}</td>
                        <td>{{$row->teacher->name}}</td>
                        <td>{{$row->course->c_name}}</td>
                        <td class="text-center"><a href="{{route('enrollment.edit',$row->id)}}" data-toggle="tooltip"
														title="Edit" class="btn btn-primary">Edit</a>
                            <a href="javascript:void(0)"
														class="dltbtn btn btn-danger" title="Delete" data-toggle="tooltip">
														Delete</i></a>	
                          </td>
                        
											</tr>
											@endforeach
											@else
											<tr>
											</td colspan="6">Users not added yet.<td>
											 </tr>

											 @endif

										</tbody>
									</table>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection    
@section('scripts')
<script>
  window.setTimeout(function() {
  $(".alert").fadeTo(500, 0).slideUp(500, function(){
    $(this).remove();
  });
  }, 2000);


</script>  
<script >
  $(document).ready(function(){
   
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

    $('.dltbtn').click(function (e){
      e.preventDefault();
     var delete_id = $(this).closest("tr").find('.delete_val').val();
      swal({
              title: "Are you sure?",
              text: "Once deleted, you will not be able to recover this data!",
              icon: "warning",
              buttons: true,
              dangerMode: true,
      })
      .then((willDelete) => {
                if (willDelete) {
                  
                  var data ={
                    "_token": $('input[name="csrf-token"]').val(), 
                    "id": delete_id,
                  }; 

                  $.ajax({
                    type:"DELETE",
                    url: 'enrollment/'+delete_id,
                    data: data,
                    success: function (response){
                      swal(response.status, {
                    icon: "success",
                  })
                  .then((result) => {
                    location.reload();
                  });

                    }

                  });


                }
         });


    });
  });
</script>
@endsection

resources/views/admin/enrollments/form.blade.php
@extends("layouts.header")
@if(!isset($enrollment->id))
@section('title', 'Add Enrollment')
@else
@section('title', 'Edit Enrollment')
@endif
@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        @if(!isset($enrollment->id))
        <div class="col-sm-6">
        <h1>Add Enrollment</h1>
          </div>
        @else
          <div class="col-sm-6">
          <h1>Edit Enrollment</h1>
          </div>
          @endif
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Basic Information</h3>
              @if(Session::has('msg'))
					<div class="col-md-12">
						<div class="alert alert-success">{{Session::get('msg')}}</div>
					</div>
					@endif
        
            </div>
            <div class="card-body">
            @if(!isset($enrollment->id))
            <form method = "post" action="{{route('enrollment.store')}}" enctype="multipart/form-data" >
            @else
             <form method = "post" action="{{route('enrollment.update',$enrollment->id)}}" enctype="multipart/form-data" >
             {{ method_field('PUT') }}
            @endif
          
             @csrf
              </div>
              <!-- start row -->
          <div class="row">
          @if(isset($enrollment->student_id))
          <div class="col-md-6">
               <div class="form-group">
                  <label>Select Student</label><span class="text-danger">*</span>
                  <select class="form-control select2"  name="student_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Student---</option>
																				@foreach($student  as $row)
																				<option value="{{$row->id}}"  {{ $row->id == $enrollment->student_id ? 'selected' : '' }}>{{$row->name}}</option>
																				@endforeach
																				</select>
                </div>
               </div>
               @else
               <div class="col-md-6">
               <div class="form-group">
                  <label>Select Student</label><span class="text-danger">*</span>
                  <select class="form-control select2"  name="student_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Student---</option>
																				@foreach($student  as $row)
																				<option value="{{$row->id}}" 'selected' : ''>{{$row->name}}</option>
																				@endforeach
																				</select>
                                        @if($errors->any())

                                                 <p class="text-danger">{{$errors->first('student')}}</p>

                                        @endif
                </div>
               </div>
               @endif
                <!-- End-Student-Col -->
                @if(isset($enrollment->course_id))
                <div class="col-md-6">
               <div class="form-group">
                  <label>Select Course</label><span class="text-danger">*</span>
                  <select class="form-control select2" name="course_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Course---</option>
																				@foreach($course  as $row)
																				<option value="{{$row->id}}"  {{ $row->id == $enrollment->course_id ? 'selected' : '' }}>{{$row->c_name}}</option>
																				@endforeach
																				</select>
                </div>
               </div><!-- End-course-Col -->
                @else
               <div class="col-md-6">
               <div class="form-group">
                  <label>Select Course</label><span class="text-danger">*</span>
                  <select class="form-control select2" name="course_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Course---</option>
																				@foreach($course  as $row)
																				<option value="{{$row->id}}" 'selected' : ''>{{$row->c_name}}</option>
																				@endforeach
																				</select>
                                        @if($errors->any())

                                                 <p class="text-danger">{{$errors->first('course')}}</p>

                                        @endif
                </div>
               </div><!-- End-course-Col -->
               @endif
                </div><!-- end row -->
               
                <div class="row">
                @if(isset($enrollment->teacher_id))
                <div class="col-md-6">
                  <div class="form-group">
                  <label>Select Teacher</label><span class="text-danger">*</span>
                  <select class="form-control select2"  name="teacher_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Teacher---</option>
																				@foreach($teacher  as $row)
																				<option value="{{$row->id}}"  {{ $row->id == $enrollment->teacher_id ? 'selected' : '' }}>{{$row->name}}</option>
																				@endforeach
																				</select>
                                        @if($errors->any())

                                                 <p class="text-danger">{{$errors->first('teacher')}}</p>

                                        @endif
                </div>
               </div><!-- End-Teacher-Col -->
                @else
                  <div class="col-md-6">
                  <div class="form-group">
                  <label>Select Teacher</label><span class="text-danger">*</span>
                  <select class="form-control select2"  name="teacher_id"  required autofocus>
                  <option value="nonselected" selected disabled>---Select Teacher---</option>
																				@foreach($teacher  as $row)
																				<option value="{{$row->id}}" 'selected' : ''>{{$row->name}}</option>
																				@endforeach
																				</select>
                                        @if($errors->any())

                                                 <p class="text-danger">{{$errors->first('teacher')}}</p>

                                        @endif
                </div>
               </div><!-- End-Teacher-Col -->
               @endif
              </div> <!-- end row -->
            </div>
            <!-- /.card-body -->
            <div class="row">
        <div class="col-12">
         <button type="submit" class="btn btn-primary" id="register" value="Register">Submit</button>
        </div>
      </div>
      </form>
          </div>
          <!-- /.card -->
        </div>
      </div>
     
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@endsection