routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\EnrollmentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();

Route::get('/allusers', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::resource('student', StudentController::class);
//courses Route
Route::resource('course', CourseController::class);
//Teacher Route
Route::resource('teacher', TeacherController::class);
//Enrollment Route
Route::resource('enrollment', EnrollmentController::class);

resources/views/admin/courses/all_courses.blade.php
@extends("layouts.header")
@section('title', 'All Courses')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Courses</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    @if(Session::has('fahad'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('fahad')}}</div>
				</div>
				@endif
				@if(Session::has('msg'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('msg')}}</div>
				</div>
				@endif
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- table data -->
        <!-- /.row (main row) -->
        <div class="card">
              <div class="card-header text-end">
                <a href="{{route('course.create')}}"  class="btn btn-primary">Add <span>+</span></a>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Operations</th>
                  </tr>
                  </thead>
                  <tbody>
											@if($course)
											@foreach($course as $row)
											<tr class="odd">
                        <input type="hidden" class="delete_val" value="{{$row->id}}">
												<td>{{$row->id}}</td>
												<td>{{$row->c_code}}</td>
                        <td>{{$row->c_name}}</td>
                        <td class="text-center"><a href="{{route('course.edit',$row->id)}}" data-toggle="tooltip"
														title="Edit" class="btn btn-primary">Edit</a>
                            <a href="javascript:void(0)"
														class=" dltbtn btn btn-danger" title="Delete" data-toggle="tooltip">
														Delete</a>	
                          </td>
                        
											</tr>
											@endforeach
											@else
											<tr>
											</td colspan="6">Users not added yet.<td>
											 </tr>

											 @endif

										</tbody>
									</table>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection    
@section('scripts')
<script>
  window.setTimeout(function() {
  $(".alert").fadeTo(500, 0).slideUp(500, function(){
    $(this).remove();
  });
  }, 2000);


</script>  
<script >
  $(document).ready(function(){
   
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

    $('.dltbtn').click(function (e){
      e.preventDefault();
     var delete_id = $(this).closest("tr").find('.delete_val').val();
      swal({
              title: "Are you sure?",
              text: "Once deleted, you will not be able to recover this data!",
              icon: "warning",
              buttons: true,
              dangerMode: true,
      })
      .then((willDelete) => {
                if (willDelete) {
                  
                  var data ={
                    "_token": $('input[name="csrf-token"]').val(), 
                    "id": delete_id,
                  }; 

                  $.ajax({
                    type:"DELETE",
                    url: 'course/'+delete_id,
                    data: data,
                    success: function (response){
                      swal(response.status, {
                    icon: "success",
                  })
                  .then((result) => {
                    location.reload();
                  });

                    }

                  });


                }
         });


    });
  });
</script>
@endsection

resources/views/admin/courses/form.blade.php
@extends("layouts.header")
@if(!isset($course->id))
@section('title', 'Add Course')
@else
@section('title', 'Edit Course')
@endif
@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        @if(!isset($course->id))
          <div class="col-sm-6">
            <h1>Add Course</h1>
          </div>
          @else
          <div class="col-sm-6">
            <h1>Edit Course</h1>
          </div>
          @endif
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Basic Information</h3>
              @if(Session::has('msg'))
					<div class="col-md-12">
						<div class="alert alert-success">{{Session::get('msg')}}</div>
					</div>
					@endif
        
            </div>
            <div class="card-body">
           
             @if(!isset($course->id))
            <form method = "post" action="{{route('course.store')}}" method="POST" enctype="multipart/form-data" >
            @else
             <form method = "post" action="{{route('course.update',$course->id)}}" enctype="multipart/form-data" >
             {{ method_field('PUT') }}
            @endif 
             @csrf
              </div>
              <!-- start row -->
              <div class="row">
               <div class="col-md-6">
               <div class="form-group">
              <label for="inputName">Course Code</label><span class="text-danger">*</span>
              <input type="text" id="Name" name="c_code" required  value="{{ isset($course->c_code) ? $course->c_code : '' }}" class="form-control num" autofocus>
              @if($errors->any())

							                 <p class="text-danger">{{$errors->first('c_code')}}</p>

											@endif
               </div>
               </div>
               <div class="col-md-6">
               <div class="form-group">
                <label for="inputDescription">Course Name</label><span class="text-danger">*</span>
                <input type="text" id="inputName" name="c_name" id ="name" required value="{{ isset($course->c_name) ? $course->c_name : '' }}" class="form-control" autofocus>
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('name')}}</p>

											@endif
              </div>
               </div>
              </div>
            
               <!-- end row -->

               <div class="row">
        <div class="col-12">
         <button type="submit" class="btn btn-primary" id="register" value="Register" disabled="disabled">Submit</button>
        </div>
        </form>
      </div>
             
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
         <button type="submit" class="btn btn-primary" id="register" value="Register" disabled="disabled">Submit</button>
        </div>
        </form>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@endsection
@section('scripts')

<script type="text/javascript">
//restrict special Characters for textbox

$('input[name="c_code"]').on('keypress',function (event){
var regex = new RegExp("^[a-zA-z0-9- ]+$");
var key = String.fromCharCode(!event.charcode ? event.which : event.charcode);
if(!regex.test(key)){
  event.preventDefault();
  return false;
}
});
$('input[name="name"]').on('keypress',function (event){
var regex = new RegExp("^[a-zA-z ]+$");
var key = String.fromCharCode(!event.charcode ? event.which : event.charcode);
if(!regex.test(key)){
  event.preventDefault();
  return false;
}
});
</script>
@endsection