routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\EnrollmentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();

Route::get('/allusers', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
Route::resource('student', StudentController::class);
//courses Route
Route::resource('course', CourseController::class);
//Teacher Route
Route::resource('teacher', TeacherController::class);
//Enrollment Route
Route::resource('enrollment', EnrollmentController::class);

app/Models/Teacher.php
<?php

namespace App\Models;
use App\Models\Teacher;
use File;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    use HasFactory;
    protected $table = 'teacher';
    protected $primaryKey = 'id';
    protected $fillable = ['image','name','designation','mobile','email','dob','address','country','state','city'];

    public static function image($request){
        $file = $request->file('image');
        $extension = $file->getClientOriginalExtension();
        $filename= time().'.'.$extension;
        $file->move('images/',$filename);
        $image =$filename;

       return $image;
    }
    public static function updateimage($request,$id){
        $teacher = Teacher::find($id);
        if ($teacher) {
            // Upload the new image
            if ($request->hasFile('image')) {
                // Delete old image
               File::delete('public/images/'.$teacher->image);
    
                // Image edit
                $image =  $request->file('image');
                $extension = $image->getClientOriginalExtension();
                $filename= time().'.'.$extension;
                $image->move('images/',$filename);
    
                $image = $filename;
                return $image;
            }
          }
      }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Validator;
use App\Helpers\Helper;
use App\Models\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $teacher= Teacher::all();
        return view('admin.teachers.all_teachers')->with('teacher',$teacher);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        return view('admin.teachers.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $help = Helper::teachercreate($request);
        $request->validate($help);
       
        $input=$request->all();
        if($request->image){
            $imageData = Teacher::image($request);
            $input['image'] = $imageData;
        }
        $new = Teacher::create($input);
        $request->session()->flash('msg','Inserted Sucessfully!!');
        return redirect()->route('teacher.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //fetching data
       $teacher=Teacher::where('id',$id)->first();
      
       return view ('admin.teachers.form')->with(compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Helper::teachercreate($request,$id);
        $request->validate($update);
        $teacher = Teacher::find($id);
    
        $input=$request->all();
        if($request->image){
            $imageData = Teacher::updateimage($request,$id);
            $input['image'] = $imageData;
              }
        $teacher->update($input);
    
            $request->session()->flash('msg','update Sucessfully!!');
             return redirect()->route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Teacher::destroy($id);

        return response()->json(['status'=>'Teacher Deleted Successfully']);
    }
}

resources/views/admin/teachers/all_teachers.blade.php
@extends("layouts.header")
@section('title', 'All Teachers')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Teachers</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    @if(Session::has('fahad'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('fahad')}}</div>
				</div>
				@endif
				@if(Session::has('msg'))
				<div class="col-md-12">
					<div class="alert alert-success">{{Session::get('msg')}}</div>
				</div>
				@endif
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- table data -->
        <!-- /.row (main row) -->
        <div class="card">
              <div class="card-header text-end">
                <a href="{{route('teacher.create')}}"  class="btn btn-primary">Add <span>+</span></a>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Designation</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Operations</th>
                  </tr>
                  </thead>
                  <tbody>
											@if($teacher)
											@foreach($teacher as $row)
											<tr class="odd">
                        <input type="hidden" class="delete_val" value="{{$row->id}}">
												<td>{{$row->id}}</td>
                        @if(!isset($row->image))
                        <td><img width="80px" src="{{URL::asset('dist/img/default.jpg')}}" alt=""></td>
                        @else
                        <td><img width="80px" src="{{ URL::asset('images/'.$row->image) }}"></td>
                        @endif
												<td>{{$row->designation}}</td>
                        <td>{{$row->name}}</td>
                        <td>{{$row->email}}</td>
                        @if($row->is_active =='0')
                        <td><span class="badge badge-warning">Hidden</span></td>
                        @else
                        <td><span class="badge badge-success">Active</span></td>
                        @endif
                        <td class="text-center"><a href="{{route('teacher.edit',$row->id)}}" data-toggle="tooltip" class="btn btn-primary">Edit</a>
                            <a href="javascript:void(0)"
														class="btn btn-danger dltbtn" title="Delete" data-toggle="tooltip">
													   Delete</a>	
                          </td>
                        
											</tr>
											@endforeach
											@else
											<tr>
											</td colspan="6">Teacher not added yet.<td>
											 </tr>

											 @endif

										</tbody>
									</table>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
@endsection    
@section('scripts')
<script>
  window.setTimeout(function() {
  $(".alert").fadeTo(500, 0).slideUp(500, function(){
    $(this).remove();
  });
  }, 2000);


</script>  
<script >
  $(document).ready(function(){
   
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

    $('.dltbtn').click(function (e){
      e.preventDefault();
     var delete_id = $(this).closest("tr").find('.delete_val').val();
      swal({
              title: "Are you sure?",
              text: "Once deleted, you will not be able to recover this data!",
              icon: "warning",
              buttons: true,
              dangerMode: true,
      })
      .then((willDelete) => {
                if (willDelete) {
                  
                  var data ={
                    "_token": $('input[name="csrf-token"]').val(), 
                    "id": delete_id,
                  }; 

                  $.ajax({
                    type:"DELETE",
                    url: 'teacher/'+delete_id,
                    data: data,
                    success: function (response){
                      swal(response.status, {
                    icon: "success",
                  })
                  .then((result) => {
                    location.reload();
                  });

                    }

                  });


                }
         });


    });
  });
</script>
@endsection

resources/views/admin/teachers/form.blade.php
@extends("layouts.header")
@if(!isset($teacher->id))
@section('title', 'Add Teacher')
@else
@section('title', 'Edit Teacher')
@endif
@section('content')
<style>
  .form-input {
  width:250px;
  padding:20px;
  background:#fff;

}
.form-input input {
  display:none;
}
.form-input label {
  display:block;
  width:70%;
  height:50px;
  line-height:50px;
  text-align:center;
  background:#333;
  color:#fff;
  font-size:13px;
  font-family:"Open Sans",sans-serif;
  text-transform:Uppercase;
  font-weight:600;
  border-radius:10px;
  cursor:pointer;
}
 
.form-input img {
  width:100%;
  margin-top:10px;
}
</style>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        @if(!isset($teacher->id))
          <div class="col-sm-6">
            <h1>Add Teacher</h1>
          </div>
          @else
          <div class="col-sm-6">
            <h1>Edit Teacher</h1>
          </div>
          @endif
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active"></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Basic Information</h3>
              @if(Session::has('msg'))
					<div class="col-md-12">
						<div class="alert alert-success">{{Session::get('msg')}}</div>
					</div>
					@endif
        
            </div>
            <div class="card-body">
        
             @if(!isset($teacher->id))
            <form method = "post" action="{{route('teacher.store')}}" enctype="multipart/form-data" >
            @else
             <form method = "post" action="{{route('teacher.update',$teacher->id)}}" enctype="multipart/form-data" >
             {{ method_field('PUT') }}
            @endif
             @csrf
            <div class="form-group">
            <div class="form-input">
            <div class="preview">
            @if(isset($teacher->image))
            <img width="50%" src="{{ URL::asset('images/'.$teacher->image) }}"> 
             @else
      <img id="file-ip-1-preview" src="{{URL::asset('dist/img/default.jpg')}}">
      @endif
    </div>          
    <label for="file-ip-1">Upload Image</label>
    <input type="file" id="file-ip-1" accept="image/*" name="image" onchange="showPreview(event);">
    
    @if($errors->any())

							         <p class="text-danger">{{$errors->first('image')}}</p> 

											@endif
  </div>
              </div>
              <!-- start row -->
              <div class="row">
               <div class="col-md-4">
               <div class="form-group">
              <label for="inputName">Teacher Name</label><span class="text-danger">*</span>
              <input type="text" id="Name" name="name" required  value="{{ isset($teacher->name) ? $teacher->name : '' }}" class="form-control">
              @if($errors->any())

							                 <p class="text-danger">{{$errors->first('name')}}</p>

											@endif
               </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputDescription">Designation</label><span class="text-danger">*</span>
                <input type="text" id="inputName" name="designation" value="{{ isset($teacher->designation) ? $teacher->designation : '' }}" required class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('designation')}}</p>

											@endif
              </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputClientCompany">Mobile No</label>
                <input type="text" id="txtPhone" name="mobile" value="{{ isset($teacher->mobile) ? $teacher->mobile : '' }}" class="form-control num">
                <span id="spnPhoneStatus"></span>
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('number')}}</p>

											@endif
              </div>
               </div>
              </div>
            
               <!-- end row -->

               <!-- start row -->
               <div class="row">
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">Email</label><span class="text-danger">*</span>
                <input type="email" name="email" value="{{ isset($teacher->email) ? $teacher->email : '' }}" class="form-control" required>
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('email')}}</p>

											@endif
              </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">DOB</label>
                <input type="text" name="dob" id="datepicker" value="{{ isset($teacher->dob) ? $teacher->dob : '' }}" class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('dob')}}</p>

											@endif
              </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">Address</label>
                <input type="text" name="address" value="{{ isset($teacher->address) ? $teacher->address : '' }}" class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('address')}}</p>

											@endif
              </div>
               </div>
               </div>
             <!-- end row -->
              
                <!-- start row -->
                <div class="row">
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">Country</label>
                <input type="text" name="country" value="{{ isset($teacher->country) ? $teacher->country : '' }}" class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('country')}}</p>

											@endif
              </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">State</label>
                <input type="text" name="state" value="{{ isset($teacher->state) ? $teacher->state : '' }}" class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('state')}}</p>

											@endif
              </div>
               </div>
               <div class="col-md-4">
               <div class="form-group">
                <label for="inputProjectLeader">City</label>
                <input type="text" name="city" value="{{ isset($teacher->city) ? $teacher->city : '' }}" class="form-control">
                @if($errors->any())

							                 <p class="text-danger">{{$errors->first('city')}}</p>

											@endif
              </div>
               </div>
               </div>
             <!-- end row -->
             
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
         <button type="submit" class="btn btn-primary" >Submit</button>
        </div>
        </form>
      </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->


@endsection
@section('scripts')
<script type="text/javascript">

function showPreview(event){
  if(event.target.files.length > 0){
    var src = URL.createObjectURL(event.target.files[0]);
    var preview = document.getElementById("file-ip-1-preview");
    preview.src = src;
    preview.style.display = "block";
  }
}

</script>
<script>
$(document).ready(function () {
        var today = new Date();
        $('#datepicker').datepicker({
            format: 'mm-dd-yyyy',
            autoclose:true,
            endDate: "today",
            maxDate: today
        }).on('changeDate', function (ev) {
                $(this).datepicker('hide');
            });


        $('#datepicker').keyup(function () {
            if (this.value.match(/[^0-9]/g)) {
                this.value = this.value.replace(/[^0-9^-]/g, '');
            }
        });
    });
</script>
<script>
$(document).ready(function() {
    $('#txtPhone').blur(function(e) {
        if (validatePhone('txtPhone')) {
        }
        else {
            $('#spnPhoneStatus').html('Invalid Number');
            $('#spnPhoneStatus').css('color', 'red');
        }
    });
});

function validatePhone(txtPhone) {
    var a = document.getElementById(txtPhone).value;
    var filter = /^((\+[1-9]{1,4}[ \-]*)|(\([0-9]{2,3}\)[ \-]*)|([0-9]{2,4})[ \-]*)*?[0-9]{3,4}?[ \-]*[0-9]{3,4}?$/;
    if (filter.test(a)) {
        return true;
    }
    else {
        return false;
    }
}
</script>

<script>  
    $(document).ready(function() {
      $('.error').hide();
      $('#submit').click(function(){
        var email = $('#email').val();
        if(email== ''){
          $('#email').next().show();
          return false;
        }
        if(IsEmail(email)==false){
          $('#invalid_email').show();
          return false;
        }
    return false;
  });
 });
 function IsEmail(email) {
  var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  if(!regex.test(email)) {
    return false;
  }else{
    return true;
  }
}
</script>
@endsection